name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      uploadAssets:
        description: 'Upload Assets'
        type: boolean
        required: false
        default: true

jobs:
  build:
    strategy:
      matrix:
        # need older ubuntu for backwards compat with glibc.
        os: [
          self-hosted-x86_64,
          macos-latest,
          macos-13,
          self-hosted-arm64,
          self-hosted-windows-x86_64,
        ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # x86_64 needs yasm
    - name: Set up Homebrew
      if: ${{ matrix.os == 'macos-13' }}
      uses: Homebrew/actions/setup-homebrew@master

    # yasm can be dropped
    - name: Install yasm and nasm
      if: ${{ matrix.os == 'macos-13' }}
      run: brew install yasm nasm

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        # node-gyp doesn't work on python 3.12 due to missing distutils on mac and windows.
        python-version: '3.10'
      # this action does not have 3.10 available for linux arm64 (or any version at time of checking).
      # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
      if: ${{ matrix.os == 'macos-latest' || matrix.os == 'macos-13' }}

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - run: SKIP_SCRYPTED_LIBAV_PREBUILD=true npm install

    - run: rm -f FFmpeg/ffmpeg
      if: ${{ matrix.os != 'self-hosted-windows-x86_64' }}

    - run: rm -Force -ErrorAction SilentlyContinue FFmpeg/ffmpeg.exe
      if: ${{ matrix.os == 'self-hosted-windows-x86_64' }}

    - run: npm run prebuildify-${{ matrix.os }}
      env:
        FFMPEG_NO_REBUILD: true

    - run: npm run prebuildify-upload -- ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event.inputs.uploadAssets != 'false' }}
